---
title: "DEGreport examples"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
    theme: readable
    highlight: zenburn
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy=TRUE, highlight=TRUE, dev="png",
                      cache=TRUE, highlight=TRUE, autodep=TRUE, 
                      warning=FALSE, error=FALSE,
                      eval=TRUE, fig.width= 9, fig.height = 5,
                      message=FALSE, prompt=TRUE, comment='', fig.cap='', bootstrap.show.code=FALSE)
options(bitmapType = 'cairo')
```

Load packages

```{r load}
.void = lapply(list("dplyr", "tidyr", "ggplot2", "DESeq2", "DEGreport"), require, character.only = TRUE)
```

load example from our teaching team at Harvard Chan School

```{r analysis}
count = read.delim("Mov10_full_counts.txt", sep="\t", row.names=1)
meta = data.frame(row.names=colnames(count), name=colnames(count)) %>%
    separate(name,sep="_",into=c("type","condition","rep"))

library(DESeq2)
dds = DESeqDataSetFromMatrix(count, meta, design = ~type + condition)
dds = DESeq(dds)

res = results(dds)
res$id = row.names(res) # add gene name for plotting
res = res[order(res$padj),] # sort by padj

norm_counts = assay(rlog(dds)) # normalize counts
```

Make some nice plots:

```{r plots, results='asis', fig.width= 9, fig.height = 5}
DEGreport::degPlot(dds = dds, res = res, n=9, xs="type", group = "condition")


pattern = DEGreport::degPatterns(norm_counts[row.names(res)[1:500],], # norm counts
                                 meta, # design
                                 time = "type", col = "condition") # plot settings

DEGreport::degVolcano(
    as.data.frame(res[,c("log2FoldChange","padj")]), # table - 2 columns
    plot_text=as.data.frame(res[1:10,c("log2FoldChange","padj","id")])) # table to add names
```